const meditationQuotes = {
    "528": [ // Stress Relief & Transformation
        "The soul always knows what to do to heal itself.",
        "Stress is who you think you should be. Relaxation is who you are.",
        "Within you, there is a stillness and a sanctuary to which you can retreat at any time.",
        "The greatest weapon against stress is our ability to choose one thought over another.",
        "Calmness is the cradle of power.",
        "Feelings are just stones in the river of the mind. Let them wash past.",
        "You don't have to control your thoughts. You just have to stop letting them control you.",
        "A calm mind brings inner strength and self-confidence.",
        "Your calm mind is the ultimate weapon against your challenges.",
        "The time to relax is when you don't have time for it.",
        "Tension is who you think you should be. Relaxation is who you are.",
        "Slow down and everything you are chasing will come around and catch you.",
        "Rule your mind or it will rule you.",
        "Nothing can bring you peace but yourself.",
        "The more tranquil a man becomes, the greater is his success.",
        "Do not let the behavior of others destroy your inner peace.",
        "Sometimes the most productive thing you can do is relax.",
        "Breath is the power behind all things.",
        "To be calm is the highest achievement of the self.",
        "Peace is a day-to-day problem, the product of a multitude of easily forgotten acts.",
        "There is more to life than increasing its speed.",
        "The mind is like water. When it’s turbulent, it’s difficult to see. When it’s calm, everything becomes clear.",
        "Every breath is a fresh beginning.",
        "Happiness is a state of relaxation.",
        "Your peace is more important than driving yourself crazy.",
        "Give your stress wings and let it fly away.",
        "He who is of a calm and happy nature will hardly feel the pressure of age.",
        "Surrender to what is. Let go of what was. Have faith in what will be.",
        "Quiet the mind, and the soul will speak.",
        "Stress is the trash of modern life - we all generate it but if you don't dispose of it properly, it will pile up."
    ],
    "396": [ // Releasing Fear & Guilt
        "Courage is not the absence of fear, but the triumph over it.",
        "Fear is a darkroom where negatives are developed.",
        "To forgive is to set a prisoner free and discover that the prisoner was you.",
        "Your past does not equal your future.",
        "The only thing we have to fear is fear itself.",
        "Guilt is to the spirit what pain is to the body.",
        "Do one thing every day that scares you.",
        "Fear is only as deep as the mind allows.",
        "Forgive yourself for not knowing what you didn't know before you learned it.",
        "The moment you accept what troubles you've been given, the door will open.",
        "Fear has two meanings: 'Forget Everything And Run' or 'Face Everything And Rise.'",
        "Stop being afraid of what could go wrong, and start being excited about what could go right.",
        "You cannot travel back in time to fix things, but you can build a better present.",
        "Guilt is a weight that prevents you from swimming; let it go to stay afloat.",
        "Everything you've ever wanted is on the other side of fear.",
        "Do not look back; you are not going that way.",
        "Mistakes are proof that you are trying.",
        "Shame is a soul-eating emotion.",
        "Peace starts with a simple 'I forgive myself.'",
        "Fear is a reaction. Courage is a decision.",
        "We are more often frightened than hurt; and we suffer more from imagination than from reality.",
        "The secret of freedom lies in educating people, whereas the secret of tyranny is in keeping them ignorant.",
        "What you fear is that which you must face.",
        "Don't let your struggle become your identity.",
        "You are allowed to be both a masterpiece and a work in progress.",
        "The only real mistake is the one from which we learn nothing.",
        "He who has overcome his fears will truly be free.",
        "Guilt is not a constructive emotion; action is.",
        "Limit your 'always' and your 'nevers.'",
        "Freedom is what you do with what's been done to you."
    ],
    "432": [ // Inner Peace & Universal Harmony
        "Nature does not hurry, yet everything is accomplished.",
        "The universe is not outside of you. Look inside; everything that you want, you already are.",
        "Silence is a source of great strength.",
        "Be like water, my friend.",
        "He who lives in harmony with himself lives in harmony with the universe.",
        "The quieter you become, the more you are able to hear.",
        "Peace comes from within. Do not seek it without.",
        "Look deep into nature, and then you will understand everything better.",
        "Earth provides enough to satisfy every man's needs, but not every man's greed.",
        "In the woods, we return to reason and faith.",
        "To the mind that is still, the whole universe surrenders.",
        "Your heart is the size of an ocean. Go find yourself in its hidden depths.",
        "The poetry of the earth is never dead.",
        "Everything in the universe has a rhythm. Everything dances.",
        "Harmony is the beautiful balance between mind, body, and soul.",
        "There is a way that nature speaks, that land speaks. Most of the time we are simply not patient enough.",
        "Radiate an energy of serenity and peace; let the universe mirror it back.",
        "Flow with whatever may happen, and let your mind be free.",
        "To be in harmony with the wholeness of things is to be truly alive.",
        "Inner peace begins the moment you choose not to allow another person or event to control your emotions.",
        "Acceptance is the key to paradise.",
        "When you realize how perfect everything is, you will tilt your head back and laugh at the sky.",
        "The stars are the land-marks of the universe.",
        "You are a child of the universe, no less than the trees and the stars.",
        "There is a voice that doesn’t use words. Listen.",
        "Live in each season as it passes; breathe the air, drink the drink, taste the fruit.",
        "Adopt the pace of nature: her secret is patience.",
        "Solitude is where I place my chaos to rest.",
        "All that is gold does not glitter, not all those who wander are lost.",
        "We are all just walking each other home."
    ],
    "639": [ // Improving Relationships & Connection
        "Where there is love there is life.",
        "Connection is why we are here; it is what gives purpose and meaning to our lives.",
        "Love is the only force capable of transforming an enemy into a friend.",
        "A kind word is like a spring day.",
        "The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed.",
        "We are built for connection.",
        "In the end, only three things matter: how much you loved, how gently you lived, and how gracefully you let go.",
        "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.",
        "To love and be loved is to feel the sun from both sides.",
        "Every person you meet is a mirror of yourself.",
        "Love and compassion are necessities, not luxuries. Without them, humanity cannot survive.",
        "A real friend is one who walks in when the rest of the world walks out.",
        "Listen with the intent to understand, not the intent to reply.",
        "Relationships are like glass. Sometimes it’s better to leave them broken than try to hurt yourself putting it back together.",
        "The best thing to hold onto in life is each other.",
        "Spread love everywhere you go.",
        "Shared joy is a double joy; shared sorrow is a half sorrow.",
        "Love is not something you find. Love is something that finds you.",
        "We can improve our relationships with others by leaps and bounds if we become encouragers rather than critics.",
        "The quality of your life is the quality of your relationships.",
        "Let us always meet each other with a smile, for the smile is the beginning of love.",
        "There is no love without forgiveness, and there is no forgiveness without love.",
        "Deep listening is the kind of listening that can help relieve the suffering of another person.",
        "True connection starts with being true to yourself.",
        "Treat everyone with politeness, even those who are rude to you.",
        "Walking with a friend in the dark is better than walking alone in the light.",
        "Love yourself first and everything else falls into line.",
        "The most important ingredient we put into any relationship is not what we say or what we do, but what we are.",
        "We rise by lifting others.",
        "Alone we can do so little; together we can do so much."
    ]
};
